// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: datapb/datapb.proto

/*
	Package datapb is a generated protocol buffer package.

	It is generated from these files:
		datapb/datapb.proto

	It has these top-level messages:
		GetReq
		GetResp
		SetReq
		SetResp
		Log
		AppendLogReq
		AppendLogResp
		GetLatestSnapshotReq
		GetLatestSnapshotResp
		GetLogReq
		GetLogResp
		GroupChangeReq
		GroupChangeResp
		MetaServerChangeReq
		MetaServerChangeResp
		ReconcileReq
		ReconcileResp
*/
package datapb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import configpb "github.com/choleraehyq/asuka/pb/configpb"
import errorpb "github.com/choleraehyq/asuka/pb/errorpb"
import storagepb "github.com/choleraehyq/asuka/pb/storagepb"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// the reason causes this group change
type GroupChangeType int32

const (
	// change self to learner or secondary; use CHANGE_TO_PRIMARY when changing to primary
	// other replica info may also change
	CHANGE_NODE GroupChangeType = 0
	// create new replica group
	CREATE_GROUP GroupChangeType = 1
	// join an existing group as learner
	ADD_TO_GROUP GroupChangeType = 2
	// delete self from an existing group
	// currently not used
	REMOVE_FROM_GROUP GroupChangeType = 3
	// change self to primary replica
	CHANGE_TO_PRIMARY GroupChangeType = 4
)

var GroupChangeType_name = map[int32]string{
	0: "CHANGE_NODE",
	1: "CREATE_GROUP",
	2: "ADD_TO_GROUP",
	3: "REMOVE_FROM_GROUP",
	4: "CHANGE_TO_PRIMARY",
}
var GroupChangeType_value = map[string]int32{
	"CHANGE_NODE":       0,
	"CREATE_GROUP":      1,
	"ADD_TO_GROUP":      2,
	"REMOVE_FROM_GROUP": 3,
	"CHANGE_TO_PRIMARY": 4,
}

func (x GroupChangeType) String() string {
	return proto.EnumName(GroupChangeType_name, int32(x))
}
func (GroupChangeType) EnumDescriptor() ([]byte, []int) { return fileDescriptorDatapb, []int{0} }

type GetReq struct {
	GroupId string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Key     []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *GetReq) Reset()                    { *m = GetReq{} }
func (m *GetReq) String() string            { return proto.CompactTextString(m) }
func (*GetReq) ProtoMessage()               {}
func (*GetReq) Descriptor() ([]byte, []int) { return fileDescriptorDatapb, []int{0} }

func (m *GetReq) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *GetReq) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type GetResp struct {
	Value []byte         `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Error *errorpb.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *GetResp) Reset()                    { *m = GetResp{} }
func (m *GetResp) String() string            { return proto.CompactTextString(m) }
func (*GetResp) ProtoMessage()               {}
func (*GetResp) Descriptor() ([]byte, []int) { return fileDescriptorDatapb, []int{1} }

func (m *GetResp) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *GetResp) GetError() *errorpb.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type SetReq struct {
	GroupId string           `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Pair    storagepb.KVPair `protobuf:"bytes,2,opt,name=pair" json:"pair"`
}

func (m *SetReq) Reset()                    { *m = SetReq{} }
func (m *SetReq) String() string            { return proto.CompactTextString(m) }
func (*SetReq) ProtoMessage()               {}
func (*SetReq) Descriptor() ([]byte, []int) { return fileDescriptorDatapb, []int{2} }

func (m *SetReq) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *SetReq) GetPair() storagepb.KVPair {
	if m != nil {
		return m.Pair
	}
	return storagepb.KVPair{}
}

type SetResp struct {
	Error *errorpb.Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *SetResp) Reset()                    { *m = SetResp{} }
func (m *SetResp) String() string            { return proto.CompactTextString(m) }
func (*SetResp) ProtoMessage()               {}
func (*SetResp) Descriptor() ([]byte, []int) { return fileDescriptorDatapb, []int{3} }

func (m *SetResp) GetError() *errorpb.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Log struct {
	Kv *storagepb.KVPair `protobuf:"bytes,1,opt,name=kv" json:"kv,omitempty"`
}

func (m *Log) Reset()                    { *m = Log{} }
func (m *Log) String() string            { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()               {}
func (*Log) Descriptor() ([]byte, []int) { return fileDescriptorDatapb, []int{4} }

func (m *Log) GetKv() *storagepb.KVPair {
	if m != nil {
		return m.Kv
	}
	return nil
}

type AppendLogReq struct {
	GroupNo  configpb.ConfigNo `protobuf:"bytes,1,opt,name=group_no,json=groupNo" json:"group_no"`
	Sn       uint64            `protobuf:"varint,2,opt,name=sn,proto3" json:"sn,omitempty"`
	Log      *Log              `protobuf:"bytes,3,opt,name=log" json:"log,omitempty"`
	CommitSn uint64            `protobuf:"varint,4,opt,name=commit_sn,json=commitSn,proto3" json:"commit_sn,omitempty"`
}

func (m *AppendLogReq) Reset()                    { *m = AppendLogReq{} }
func (m *AppendLogReq) String() string            { return proto.CompactTextString(m) }
func (*AppendLogReq) ProtoMessage()               {}
func (*AppendLogReq) Descriptor() ([]byte, []int) { return fileDescriptorDatapb, []int{5} }

func (m *AppendLogReq) GetGroupNo() configpb.ConfigNo {
	if m != nil {
		return m.GroupNo
	}
	return configpb.ConfigNo{}
}

func (m *AppendLogReq) GetSn() uint64 {
	if m != nil {
		return m.Sn
	}
	return 0
}

func (m *AppendLogReq) GetLog() *Log {
	if m != nil {
		return m.Log
	}
	return nil
}

func (m *AppendLogReq) GetCommitSn() uint64 {
	if m != nil {
		return m.CommitSn
	}
	return 0
}

type AppendLogResp struct {
	Sn    uint64         `protobuf:"varint,3,opt,name=sn,proto3" json:"sn,omitempty"`
	Error *errorpb.Error `protobuf:"bytes,100,opt,name=error" json:"error,omitempty"`
}

func (m *AppendLogResp) Reset()                    { *m = AppendLogResp{} }
func (m *AppendLogResp) String() string            { return proto.CompactTextString(m) }
func (*AppendLogResp) ProtoMessage()               {}
func (*AppendLogResp) Descriptor() ([]byte, []int) { return fileDescriptorDatapb, []int{6} }

func (m *AppendLogResp) GetSn() uint64 {
	if m != nil {
		return m.Sn
	}
	return 0
}

func (m *AppendLogResp) GetError() *errorpb.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type GetLatestSnapshotReq struct {
	GroupNo configpb.ConfigNo `protobuf:"bytes,1,opt,name=group_no,json=groupNo" json:"group_no"`
}

func (m *GetLatestSnapshotReq) Reset()                    { *m = GetLatestSnapshotReq{} }
func (m *GetLatestSnapshotReq) String() string            { return proto.CompactTextString(m) }
func (*GetLatestSnapshotReq) ProtoMessage()               {}
func (*GetLatestSnapshotReq) Descriptor() ([]byte, []int) { return fileDescriptorDatapb, []int{7} }

func (m *GetLatestSnapshotReq) GetGroupNo() configpb.ConfigNo {
	if m != nil {
		return m.GroupNo
	}
	return configpb.ConfigNo{}
}

type GetLatestSnapshotResp struct {
	GroupNo  configpb.ConfigNo   `protobuf:"bytes,1,opt,name=group_no,json=groupNo" json:"group_no"`
	Snapshot *storagepb.Snapshot `protobuf:"bytes,2,opt,name=snapshot" json:"snapshot,omitempty"`
	Error    *errorpb.Error      `protobuf:"bytes,100,opt,name=error" json:"error,omitempty"`
}

func (m *GetLatestSnapshotResp) Reset()                    { *m = GetLatestSnapshotResp{} }
func (m *GetLatestSnapshotResp) String() string            { return proto.CompactTextString(m) }
func (*GetLatestSnapshotResp) ProtoMessage()               {}
func (*GetLatestSnapshotResp) Descriptor() ([]byte, []int) { return fileDescriptorDatapb, []int{8} }

func (m *GetLatestSnapshotResp) GetGroupNo() configpb.ConfigNo {
	if m != nil {
		return m.GroupNo
	}
	return configpb.ConfigNo{}
}

func (m *GetLatestSnapshotResp) GetSnapshot() *storagepb.Snapshot {
	if m != nil {
		return m.Snapshot
	}
	return nil
}

func (m *GetLatestSnapshotResp) GetError() *errorpb.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type GetLogReq struct {
	GroupNo configpb.ConfigNo `protobuf:"bytes,1,opt,name=group_no,json=groupNo" json:"group_no"`
	Sn      uint64            `protobuf:"varint,2,opt,name=sn,proto3" json:"sn,omitempty"`
}

func (m *GetLogReq) Reset()                    { *m = GetLogReq{} }
func (m *GetLogReq) String() string            { return proto.CompactTextString(m) }
func (*GetLogReq) ProtoMessage()               {}
func (*GetLogReq) Descriptor() ([]byte, []int) { return fileDescriptorDatapb, []int{9} }

func (m *GetLogReq) GetGroupNo() configpb.ConfigNo {
	if m != nil {
		return m.GroupNo
	}
	return configpb.ConfigNo{}
}

func (m *GetLogReq) GetSn() uint64 {
	if m != nil {
		return m.Sn
	}
	return 0
}

type GetLogResp struct {
	PrepareSn uint64         `protobuf:"varint,1,opt,name=prepare_sn,json=prepareSn,proto3" json:"prepare_sn,omitempty"`
	CommitSn  uint64         `protobuf:"varint,2,opt,name=commit_sn,json=commitSn,proto3" json:"commit_sn,omitempty"`
	Sn        uint64         `protobuf:"varint,3,opt,name=sn,proto3" json:"sn,omitempty"`
	Log       *Log           `protobuf:"bytes,4,opt,name=log" json:"log,omitempty"`
	Error     *errorpb.Error `protobuf:"bytes,5,opt,name=error" json:"error,omitempty"`
}

func (m *GetLogResp) Reset()                    { *m = GetLogResp{} }
func (m *GetLogResp) String() string            { return proto.CompactTextString(m) }
func (*GetLogResp) ProtoMessage()               {}
func (*GetLogResp) Descriptor() ([]byte, []int) { return fileDescriptorDatapb, []int{10} }

func (m *GetLogResp) GetPrepareSn() uint64 {
	if m != nil {
		return m.PrepareSn
	}
	return 0
}

func (m *GetLogResp) GetCommitSn() uint64 {
	if m != nil {
		return m.CommitSn
	}
	return 0
}

func (m *GetLogResp) GetSn() uint64 {
	if m != nil {
		return m.Sn
	}
	return 0
}

func (m *GetLogResp) GetLog() *Log {
	if m != nil {
		return m.Log
	}
	return nil
}

func (m *GetLogResp) GetError() *errorpb.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type GroupChangeReq struct {
	GroupInfo *configpb.GroupInfo `protobuf:"bytes,1,opt,name=group_info,json=groupInfo" json:"group_info,omitempty"`
	Reason    GroupChangeType     `protobuf:"varint,2,opt,name=reason,proto3,enum=datapb.GroupChangeType" json:"reason,omitempty"`
}

func (m *GroupChangeReq) Reset()                    { *m = GroupChangeReq{} }
func (m *GroupChangeReq) String() string            { return proto.CompactTextString(m) }
func (*GroupChangeReq) ProtoMessage()               {}
func (*GroupChangeReq) Descriptor() ([]byte, []int) { return fileDescriptorDatapb, []int{11} }

func (m *GroupChangeReq) GetGroupInfo() *configpb.GroupInfo {
	if m != nil {
		return m.GroupInfo
	}
	return nil
}

func (m *GroupChangeReq) GetReason() GroupChangeType {
	if m != nil {
		return m.Reason
	}
	return CHANGE_NODE
}

type GroupChangeResp struct {
	Error *errorpb.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *GroupChangeResp) Reset()                    { *m = GroupChangeResp{} }
func (m *GroupChangeResp) String() string            { return proto.CompactTextString(m) }
func (*GroupChangeResp) ProtoMessage()               {}
func (*GroupChangeResp) Descriptor() ([]byte, []int) { return fileDescriptorDatapb, []int{12} }

func (m *GroupChangeResp) GetError() *errorpb.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type MetaServerChangeReq struct {
	Primary     string   `protobuf:"bytes,1,opt,name=primary,proto3" json:"primary,omitempty"`
	NewMetaList []string `protobuf:"bytes,2,rep,name=new_meta_list,json=newMetaList" json:"new_meta_list,omitempty"`
}

func (m *MetaServerChangeReq) Reset()                    { *m = MetaServerChangeReq{} }
func (m *MetaServerChangeReq) String() string            { return proto.CompactTextString(m) }
func (*MetaServerChangeReq) ProtoMessage()               {}
func (*MetaServerChangeReq) Descriptor() ([]byte, []int) { return fileDescriptorDatapb, []int{13} }

func (m *MetaServerChangeReq) GetPrimary() string {
	if m != nil {
		return m.Primary
	}
	return ""
}

func (m *MetaServerChangeReq) GetNewMetaList() []string {
	if m != nil {
		return m.NewMetaList
	}
	return nil
}

type MetaServerChangeResp struct {
	NewMetaList []string       `protobuf:"bytes,1,rep,name=new_meta_list,json=newMetaList" json:"new_meta_list,omitempty"`
	Error       *errorpb.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *MetaServerChangeResp) Reset()                    { *m = MetaServerChangeResp{} }
func (m *MetaServerChangeResp) String() string            { return proto.CompactTextString(m) }
func (*MetaServerChangeResp) ProtoMessage()               {}
func (*MetaServerChangeResp) Descriptor() ([]byte, []int) { return fileDescriptorDatapb, []int{14} }

func (m *MetaServerChangeResp) GetNewMetaList() []string {
	if m != nil {
		return m.NewMetaList
	}
	return nil
}

func (m *MetaServerChangeResp) GetError() *errorpb.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type ReconcileReq struct {
	GroupNo configpb.ConfigNo `protobuf:"bytes,1,opt,name=group_no,json=groupNo" json:"group_no"`
	Sn      uint64            `protobuf:"varint,2,opt,name=sn,proto3" json:"sn,omitempty"`
}

func (m *ReconcileReq) Reset()                    { *m = ReconcileReq{} }
func (m *ReconcileReq) String() string            { return proto.CompactTextString(m) }
func (*ReconcileReq) ProtoMessage()               {}
func (*ReconcileReq) Descriptor() ([]byte, []int) { return fileDescriptorDatapb, []int{15} }

func (m *ReconcileReq) GetGroupNo() configpb.ConfigNo {
	if m != nil {
		return m.GroupNo
	}
	return configpb.ConfigNo{}
}

func (m *ReconcileReq) GetSn() uint64 {
	if m != nil {
		return m.Sn
	}
	return 0
}

type ReconcileResp struct {
	Error *errorpb.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *ReconcileResp) Reset()                    { *m = ReconcileResp{} }
func (m *ReconcileResp) String() string            { return proto.CompactTextString(m) }
func (*ReconcileResp) ProtoMessage()               {}
func (*ReconcileResp) Descriptor() ([]byte, []int) { return fileDescriptorDatapb, []int{16} }

func (m *ReconcileResp) GetError() *errorpb.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*GetReq)(nil), "datapb.GetReq")
	proto.RegisterType((*GetResp)(nil), "datapb.GetResp")
	proto.RegisterType((*SetReq)(nil), "datapb.SetReq")
	proto.RegisterType((*SetResp)(nil), "datapb.SetResp")
	proto.RegisterType((*Log)(nil), "datapb.Log")
	proto.RegisterType((*AppendLogReq)(nil), "datapb.AppendLogReq")
	proto.RegisterType((*AppendLogResp)(nil), "datapb.AppendLogResp")
	proto.RegisterType((*GetLatestSnapshotReq)(nil), "datapb.GetLatestSnapshotReq")
	proto.RegisterType((*GetLatestSnapshotResp)(nil), "datapb.GetLatestSnapshotResp")
	proto.RegisterType((*GetLogReq)(nil), "datapb.GetLogReq")
	proto.RegisterType((*GetLogResp)(nil), "datapb.GetLogResp")
	proto.RegisterType((*GroupChangeReq)(nil), "datapb.GroupChangeReq")
	proto.RegisterType((*GroupChangeResp)(nil), "datapb.GroupChangeResp")
	proto.RegisterType((*MetaServerChangeReq)(nil), "datapb.MetaServerChangeReq")
	proto.RegisterType((*MetaServerChangeResp)(nil), "datapb.MetaServerChangeResp")
	proto.RegisterType((*ReconcileReq)(nil), "datapb.ReconcileReq")
	proto.RegisterType((*ReconcileResp)(nil), "datapb.ReconcileResp")
	proto.RegisterEnum("datapb.GroupChangeType", GroupChangeType_name, GroupChangeType_value)
}
func (m *GetReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.GroupId) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintDatapb(dAtA, i, uint64(len(m.GroupId)))
		i += copy(dAtA[i:], m.GroupId)
	}
	if len(m.Key) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintDatapb(dAtA, i, uint64(len(m.Key)))
		i += copy(dAtA[i:], m.Key)
	}
	return i, nil
}

func (m *GetResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetResp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Value) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintDatapb(dAtA, i, uint64(len(m.Value)))
		i += copy(dAtA[i:], m.Value)
	}
	if m.Error != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintDatapb(dAtA, i, uint64(m.Error.Size()))
		n1, err := m.Error.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	return i, nil
}

func (m *SetReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SetReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.GroupId) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintDatapb(dAtA, i, uint64(len(m.GroupId)))
		i += copy(dAtA[i:], m.GroupId)
	}
	dAtA[i] = 0x12
	i++
	i = encodeVarintDatapb(dAtA, i, uint64(m.Pair.Size()))
	n2, err := m.Pair.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n2
	return i, nil
}

func (m *SetResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SetResp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Error != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintDatapb(dAtA, i, uint64(m.Error.Size()))
		n3, err := m.Error.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	return i, nil
}

func (m *Log) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Log) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Kv != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintDatapb(dAtA, i, uint64(m.Kv.Size()))
		n4, err := m.Kv.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n4
	}
	return i, nil
}

func (m *AppendLogReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AppendLogReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintDatapb(dAtA, i, uint64(m.GroupNo.Size()))
	n5, err := m.GroupNo.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n5
	if m.Sn != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintDatapb(dAtA, i, uint64(m.Sn))
	}
	if m.Log != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintDatapb(dAtA, i, uint64(m.Log.Size()))
		n6, err := m.Log.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n6
	}
	if m.CommitSn != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintDatapb(dAtA, i, uint64(m.CommitSn))
	}
	return i, nil
}

func (m *AppendLogResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AppendLogResp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Sn != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintDatapb(dAtA, i, uint64(m.Sn))
	}
	if m.Error != nil {
		dAtA[i] = 0xa2
		i++
		dAtA[i] = 0x6
		i++
		i = encodeVarintDatapb(dAtA, i, uint64(m.Error.Size()))
		n7, err := m.Error.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n7
	}
	return i, nil
}

func (m *GetLatestSnapshotReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetLatestSnapshotReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintDatapb(dAtA, i, uint64(m.GroupNo.Size()))
	n8, err := m.GroupNo.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n8
	return i, nil
}

func (m *GetLatestSnapshotResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetLatestSnapshotResp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintDatapb(dAtA, i, uint64(m.GroupNo.Size()))
	n9, err := m.GroupNo.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n9
	if m.Snapshot != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintDatapb(dAtA, i, uint64(m.Snapshot.Size()))
		n10, err := m.Snapshot.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n10
	}
	if m.Error != nil {
		dAtA[i] = 0xa2
		i++
		dAtA[i] = 0x6
		i++
		i = encodeVarintDatapb(dAtA, i, uint64(m.Error.Size()))
		n11, err := m.Error.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n11
	}
	return i, nil
}

func (m *GetLogReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetLogReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintDatapb(dAtA, i, uint64(m.GroupNo.Size()))
	n12, err := m.GroupNo.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n12
	if m.Sn != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintDatapb(dAtA, i, uint64(m.Sn))
	}
	return i, nil
}

func (m *GetLogResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetLogResp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.PrepareSn != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintDatapb(dAtA, i, uint64(m.PrepareSn))
	}
	if m.CommitSn != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintDatapb(dAtA, i, uint64(m.CommitSn))
	}
	if m.Sn != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintDatapb(dAtA, i, uint64(m.Sn))
	}
	if m.Log != nil {
		dAtA[i] = 0x22
		i++
		i = encodeVarintDatapb(dAtA, i, uint64(m.Log.Size()))
		n13, err := m.Log.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n13
	}
	if m.Error != nil {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintDatapb(dAtA, i, uint64(m.Error.Size()))
		n14, err := m.Error.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n14
	}
	return i, nil
}

func (m *GroupChangeReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GroupChangeReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.GroupInfo != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintDatapb(dAtA, i, uint64(m.GroupInfo.Size()))
		n15, err := m.GroupInfo.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n15
	}
	if m.Reason != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintDatapb(dAtA, i, uint64(m.Reason))
	}
	return i, nil
}

func (m *GroupChangeResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GroupChangeResp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Error != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintDatapb(dAtA, i, uint64(m.Error.Size()))
		n16, err := m.Error.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n16
	}
	return i, nil
}

func (m *MetaServerChangeReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MetaServerChangeReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Primary) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintDatapb(dAtA, i, uint64(len(m.Primary)))
		i += copy(dAtA[i:], m.Primary)
	}
	if len(m.NewMetaList) > 0 {
		for _, s := range m.NewMetaList {
			dAtA[i] = 0x12
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	return i, nil
}

func (m *MetaServerChangeResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MetaServerChangeResp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.NewMetaList) > 0 {
		for _, s := range m.NewMetaList {
			dAtA[i] = 0xa
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	if m.Error != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintDatapb(dAtA, i, uint64(m.Error.Size()))
		n17, err := m.Error.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n17
	}
	return i, nil
}

func (m *ReconcileReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReconcileReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintDatapb(dAtA, i, uint64(m.GroupNo.Size()))
	n18, err := m.GroupNo.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n18
	if m.Sn != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintDatapb(dAtA, i, uint64(m.Sn))
	}
	return i, nil
}

func (m *ReconcileResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReconcileResp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Error != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintDatapb(dAtA, i, uint64(m.Error.Size()))
		n19, err := m.Error.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n19
	}
	return i, nil
}

func encodeVarintDatapb(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *GetReq) Size() (n int) {
	var l int
	_ = l
	l = len(m.GroupId)
	if l > 0 {
		n += 1 + l + sovDatapb(uint64(l))
	}
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovDatapb(uint64(l))
	}
	return n
}

func (m *GetResp) Size() (n int) {
	var l int
	_ = l
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovDatapb(uint64(l))
	}
	if m.Error != nil {
		l = m.Error.Size()
		n += 1 + l + sovDatapb(uint64(l))
	}
	return n
}

func (m *SetReq) Size() (n int) {
	var l int
	_ = l
	l = len(m.GroupId)
	if l > 0 {
		n += 1 + l + sovDatapb(uint64(l))
	}
	l = m.Pair.Size()
	n += 1 + l + sovDatapb(uint64(l))
	return n
}

func (m *SetResp) Size() (n int) {
	var l int
	_ = l
	if m.Error != nil {
		l = m.Error.Size()
		n += 1 + l + sovDatapb(uint64(l))
	}
	return n
}

func (m *Log) Size() (n int) {
	var l int
	_ = l
	if m.Kv != nil {
		l = m.Kv.Size()
		n += 1 + l + sovDatapb(uint64(l))
	}
	return n
}

func (m *AppendLogReq) Size() (n int) {
	var l int
	_ = l
	l = m.GroupNo.Size()
	n += 1 + l + sovDatapb(uint64(l))
	if m.Sn != 0 {
		n += 1 + sovDatapb(uint64(m.Sn))
	}
	if m.Log != nil {
		l = m.Log.Size()
		n += 1 + l + sovDatapb(uint64(l))
	}
	if m.CommitSn != 0 {
		n += 1 + sovDatapb(uint64(m.CommitSn))
	}
	return n
}

func (m *AppendLogResp) Size() (n int) {
	var l int
	_ = l
	if m.Sn != 0 {
		n += 1 + sovDatapb(uint64(m.Sn))
	}
	if m.Error != nil {
		l = m.Error.Size()
		n += 2 + l + sovDatapb(uint64(l))
	}
	return n
}

func (m *GetLatestSnapshotReq) Size() (n int) {
	var l int
	_ = l
	l = m.GroupNo.Size()
	n += 1 + l + sovDatapb(uint64(l))
	return n
}

func (m *GetLatestSnapshotResp) Size() (n int) {
	var l int
	_ = l
	l = m.GroupNo.Size()
	n += 1 + l + sovDatapb(uint64(l))
	if m.Snapshot != nil {
		l = m.Snapshot.Size()
		n += 1 + l + sovDatapb(uint64(l))
	}
	if m.Error != nil {
		l = m.Error.Size()
		n += 2 + l + sovDatapb(uint64(l))
	}
	return n
}

func (m *GetLogReq) Size() (n int) {
	var l int
	_ = l
	l = m.GroupNo.Size()
	n += 1 + l + sovDatapb(uint64(l))
	if m.Sn != 0 {
		n += 1 + sovDatapb(uint64(m.Sn))
	}
	return n
}

func (m *GetLogResp) Size() (n int) {
	var l int
	_ = l
	if m.PrepareSn != 0 {
		n += 1 + sovDatapb(uint64(m.PrepareSn))
	}
	if m.CommitSn != 0 {
		n += 1 + sovDatapb(uint64(m.CommitSn))
	}
	if m.Sn != 0 {
		n += 1 + sovDatapb(uint64(m.Sn))
	}
	if m.Log != nil {
		l = m.Log.Size()
		n += 1 + l + sovDatapb(uint64(l))
	}
	if m.Error != nil {
		l = m.Error.Size()
		n += 1 + l + sovDatapb(uint64(l))
	}
	return n
}

func (m *GroupChangeReq) Size() (n int) {
	var l int
	_ = l
	if m.GroupInfo != nil {
		l = m.GroupInfo.Size()
		n += 1 + l + sovDatapb(uint64(l))
	}
	if m.Reason != 0 {
		n += 1 + sovDatapb(uint64(m.Reason))
	}
	return n
}

func (m *GroupChangeResp) Size() (n int) {
	var l int
	_ = l
	if m.Error != nil {
		l = m.Error.Size()
		n += 1 + l + sovDatapb(uint64(l))
	}
	return n
}

func (m *MetaServerChangeReq) Size() (n int) {
	var l int
	_ = l
	l = len(m.Primary)
	if l > 0 {
		n += 1 + l + sovDatapb(uint64(l))
	}
	if len(m.NewMetaList) > 0 {
		for _, s := range m.NewMetaList {
			l = len(s)
			n += 1 + l + sovDatapb(uint64(l))
		}
	}
	return n
}

func (m *MetaServerChangeResp) Size() (n int) {
	var l int
	_ = l
	if len(m.NewMetaList) > 0 {
		for _, s := range m.NewMetaList {
			l = len(s)
			n += 1 + l + sovDatapb(uint64(l))
		}
	}
	if m.Error != nil {
		l = m.Error.Size()
		n += 1 + l + sovDatapb(uint64(l))
	}
	return n
}

func (m *ReconcileReq) Size() (n int) {
	var l int
	_ = l
	l = m.GroupNo.Size()
	n += 1 + l + sovDatapb(uint64(l))
	if m.Sn != 0 {
		n += 1 + sovDatapb(uint64(m.Sn))
	}
	return n
}

func (m *ReconcileResp) Size() (n int) {
	var l int
	_ = l
	if m.Error != nil {
		l = m.Error.Size()
		n += 1 + l + sovDatapb(uint64(l))
	}
	return n
}

func sovDatapb(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozDatapb(x uint64) (n int) {
	return sovDatapb(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GetReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDatapb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDatapb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GroupId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDatapb
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = append(m.Key[:0], dAtA[iNdEx:postIndex]...)
			if m.Key == nil {
				m.Key = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDatapb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDatapb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDatapb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDatapb
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = append(m.Value[:0], dAtA[iNdEx:postIndex]...)
			if m.Value == nil {
				m.Value = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDatapb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Error == nil {
				m.Error = &errorpb.Error{}
			}
			if err := m.Error.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDatapb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDatapb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SetReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDatapb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SetReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SetReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDatapb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GroupId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pair", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDatapb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Pair.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDatapb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDatapb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SetResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDatapb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SetResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SetResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDatapb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Error == nil {
				m.Error = &errorpb.Error{}
			}
			if err := m.Error.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDatapb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDatapb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Log) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDatapb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Log: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Log: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kv", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDatapb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Kv == nil {
				m.Kv = &storagepb.KVPair{}
			}
			if err := m.Kv.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDatapb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDatapb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AppendLogReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDatapb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AppendLogReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AppendLogReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupNo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDatapb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GroupNo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sn", wireType)
			}
			m.Sn = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sn |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Log", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDatapb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Log == nil {
				m.Log = &Log{}
			}
			if err := m.Log.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitSn", wireType)
			}
			m.CommitSn = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CommitSn |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDatapb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDatapb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AppendLogResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDatapb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AppendLogResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AppendLogResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sn", wireType)
			}
			m.Sn = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sn |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 100:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDatapb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Error == nil {
				m.Error = &errorpb.Error{}
			}
			if err := m.Error.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDatapb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDatapb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetLatestSnapshotReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDatapb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetLatestSnapshotReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetLatestSnapshotReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupNo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDatapb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GroupNo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDatapb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDatapb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetLatestSnapshotResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDatapb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetLatestSnapshotResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetLatestSnapshotResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupNo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDatapb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GroupNo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Snapshot", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDatapb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Snapshot == nil {
				m.Snapshot = &storagepb.Snapshot{}
			}
			if err := m.Snapshot.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 100:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDatapb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Error == nil {
				m.Error = &errorpb.Error{}
			}
			if err := m.Error.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDatapb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDatapb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetLogReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDatapb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetLogReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetLogReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupNo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDatapb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GroupNo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sn", wireType)
			}
			m.Sn = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sn |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDatapb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDatapb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetLogResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDatapb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetLogResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetLogResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrepareSn", wireType)
			}
			m.PrepareSn = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PrepareSn |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitSn", wireType)
			}
			m.CommitSn = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CommitSn |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sn", wireType)
			}
			m.Sn = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sn |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Log", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDatapb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Log == nil {
				m.Log = &Log{}
			}
			if err := m.Log.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDatapb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Error == nil {
				m.Error = &errorpb.Error{}
			}
			if err := m.Error.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDatapb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDatapb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GroupChangeReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDatapb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GroupChangeReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GroupChangeReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDatapb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.GroupInfo == nil {
				m.GroupInfo = &configpb.GroupInfo{}
			}
			if err := m.GroupInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			m.Reason = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Reason |= (GroupChangeType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDatapb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDatapb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GroupChangeResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDatapb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GroupChangeResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GroupChangeResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDatapb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Error == nil {
				m.Error = &errorpb.Error{}
			}
			if err := m.Error.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDatapb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDatapb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MetaServerChangeReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDatapb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MetaServerChangeReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MetaServerChangeReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Primary", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDatapb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Primary = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewMetaList", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDatapb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewMetaList = append(m.NewMetaList, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDatapb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDatapb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MetaServerChangeResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDatapb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MetaServerChangeResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MetaServerChangeResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewMetaList", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDatapb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewMetaList = append(m.NewMetaList, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDatapb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Error == nil {
				m.Error = &errorpb.Error{}
			}
			if err := m.Error.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDatapb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDatapb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReconcileReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDatapb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReconcileReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReconcileReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupNo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDatapb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GroupNo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sn", wireType)
			}
			m.Sn = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sn |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDatapb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDatapb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReconcileResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDatapb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReconcileResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReconcileResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDatapb
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Error == nil {
				m.Error = &errorpb.Error{}
			}
			if err := m.Error.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDatapb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDatapb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDatapb(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDatapb
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDatapb
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthDatapb
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowDatapb
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipDatapb(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthDatapb = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDatapb   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("datapb/datapb.proto", fileDescriptorDatapb) }

var fileDescriptorDatapb = []byte{
	// 889 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x4f, 0x6f, 0x1a, 0x47,
	0x14, 0xf7, 0x02, 0xc6, 0xe6, 0x81, 0x31, 0x1e, 0xe3, 0x86, 0x92, 0x98, 0xa6, 0xab, 0xaa, 0xb2,
	0x5a, 0x95, 0x95, 0x1c, 0x59, 0x69, 0x2f, 0x95, 0x88, 0xbd, 0xa5, 0x56, 0x8c, 0x41, 0xb3, 0x6e,
	0xa4, 0x9e, 0xb6, 0x03, 0x8c, 0x97, 0x95, 0x61, 0x67, 0xb2, 0xb3, 0x38, 0xf2, 0xa7, 0xe8, 0xb5,
	0x97, 0x9e, 0xfa, 0x65, 0x72, 0xcc, 0x27, 0xa8, 0x5a, 0xe7, 0x8b, 0x44, 0x3b, 0x3b, 0xbb, 0x2c,
	0x86, 0x60, 0x2b, 0xca, 0x69, 0xe7, 0xbd, 0x79, 0xbf, 0x37, 0xbf, 0xf7, 0x57, 0x0b, 0xbb, 0x43,
	0x12, 0x10, 0xde, 0x37, 0xa2, 0x4f, 0x93, 0xfb, 0x2c, 0x60, 0x28, 0x1f, 0x49, 0xf5, 0x1f, 0x1c,
	0x37, 0x18, 0x4d, 0xfb, 0xcd, 0x01, 0x9b, 0x18, 0x0e, 0x73, 0x98, 0x21, 0xaf, 0xfb, 0xd3, 0x4b,
	0x29, 0x49, 0x41, 0x9e, 0x22, 0x58, 0xfd, 0x79, 0xca, 0x7c, 0x30, 0x62, 0x63, 0xea, 0x13, 0x3a,
	0xba, 0x79, 0x6d, 0x10, 0x31, 0xbd, 0x22, 0x06, 0xef, 0x1b, 0x03, 0xe6, 0x5d, 0xba, 0x4e, 0xea,
	0xa0, 0x80, 0x47, 0xf7, 0x01, 0xa9, 0xef, 0x33, 0x7f, 0xf6, 0x55, 0xb0, 0x9f, 0xee, 0x83, 0x89,
	0x80, 0xf9, 0xc4, 0xa1, 0xe9, 0x53, 0x04, 0xd5, 0x8f, 0x20, 0xdf, 0xa6, 0x01, 0xa6, 0xaf, 0xd1,
	0x97, 0xb0, 0xe9, 0xf8, 0x6c, 0xca, 0x6d, 0x77, 0x58, 0xd3, 0x9e, 0x6a, 0x07, 0x05, 0xbc, 0x21,
	0xe5, 0xd3, 0x21, 0xaa, 0x40, 0xf6, 0x8a, 0xde, 0xd4, 0x32, 0x4f, 0xb5, 0x83, 0x12, 0x0e, 0x8f,
	0xba, 0x09, 0x1b, 0x12, 0x26, 0x38, 0xaa, 0xc2, 0xfa, 0x35, 0x19, 0x4f, 0xa9, 0x04, 0x95, 0x70,
	0x24, 0xa0, 0x6f, 0x60, 0x5d, 0x72, 0x94, 0xa0, 0xe2, 0x61, 0xb9, 0x19, 0x33, 0x36, 0xc3, 0x2f,
	0x8e, 0x2e, 0xf5, 0x1e, 0xe4, 0xad, 0x7b, 0x5f, 0xff, 0x1e, 0x72, 0x9c, 0xb8, 0xb1, 0xa7, 0x9d,
	0xe6, 0x2c, 0x84, 0x97, 0xaf, 0x7a, 0xc4, 0xf5, 0x5f, 0xe4, 0xde, 0xfe, 0xfb, 0xd5, 0x1a, 0x96,
	0x46, 0xba, 0x01, 0x1b, 0x96, 0x22, 0x96, 0x50, 0xd0, 0x56, 0x51, 0x38, 0x80, 0xec, 0x19, 0x73,
	0xd0, 0xd7, 0x90, 0xb9, 0xba, 0x56, 0x96, 0x8b, 0x4f, 0xe0, 0xcc, 0xd5, 0xb5, 0xfe, 0xa7, 0x06,
	0xa5, 0x16, 0xe7, 0xd4, 0x1b, 0x9e, 0x31, 0x27, 0xe4, 0xfc, 0x2c, 0xe6, 0xec, 0x31, 0x85, 0x44,
	0xcd, 0xa4, 0xa0, 0xc7, 0xf2, 0x70, 0xce, 0x14, 0xbb, 0x28, 0x9a, 0x73, 0x86, 0xca, 0x90, 0x11,
	0x9e, 0x8c, 0x25, 0x87, 0x33, 0xc2, 0x43, 0xfb, 0x90, 0x1d, 0x33, 0xa7, 0x96, 0x95, 0xf8, 0x62,
	0x53, 0xb5, 0x5f, 0xf8, 0x42, 0xa8, 0x47, 0x8f, 0xa1, 0x30, 0x60, 0x93, 0x89, 0x1b, 0xd8, 0xc2,
	0xab, 0xe5, 0x24, 0x6a, 0x33, 0x52, 0x58, 0x9e, 0x6e, 0xc2, 0x56, 0x8a, 0x90, 0xe0, 0xca, 0x79,
	0x36, 0x71, 0x9e, 0xa4, 0x60, 0xb8, 0x2a, 0x05, 0x2f, 0xa1, 0xda, 0xa6, 0xc1, 0x19, 0x09, 0xa8,
	0x08, 0x2c, 0x8f, 0x70, 0x31, 0x62, 0xc1, 0xa7, 0xc6, 0xa7, 0xff, 0xa3, 0xc1, 0xde, 0x12, 0x6f,
	0x82, 0x7f, 0x5a, 0xba, 0x0c, 0xd8, 0x14, 0xca, 0x89, 0x6a, 0x80, 0xdd, 0x54, 0x75, 0x12, 0xff,
	0x89, 0xd1, 0x03, 0x43, 0xee, 0x41, 0x21, 0x24, 0xf9, 0xf9, 0xea, 0xa8, 0xff, 0xad, 0x01, 0xc4,
	0x2e, 0x05, 0x47, 0xfb, 0x00, 0xdc, 0xa7, 0x9c, 0xf8, 0x34, 0x2c, 0x9c, 0x26, 0xcd, 0x0a, 0x4a,
	0x63, 0x79, 0xf3, 0x65, 0xcd, 0xcc, 0x97, 0x75, 0xa1, 0x8a, 0xaa, 0x45, 0x72, 0x1f, 0x69, 0x91,
	0x24, 0xe2, 0xf5, 0x55, 0x11, 0x4f, 0xa1, 0xdc, 0x0e, 0xa9, 0x1f, 0x8f, 0x88, 0xe7, 0xd0, 0x30,
	0xec, 0x43, 0x00, 0x35, 0x72, 0xde, 0x65, 0x1c, 0xf8, 0xee, 0x2c, 0x70, 0x69, 0x7d, 0xea, 0x5d,
	0x32, 0x5c, 0x70, 0xe2, 0x23, 0x32, 0x20, 0xef, 0x53, 0x22, 0x58, 0x44, 0xba, 0x7c, 0xf8, 0x28,
	0x66, 0x93, 0xf2, 0x7d, 0x71, 0xc3, 0x29, 0x56, 0x66, 0xfa, 0x73, 0xd8, 0x9e, 0x7b, 0x36, 0x3d,
	0x97, 0x2b, 0x57, 0x83, 0x05, 0xbb, 0x1d, 0x1a, 0x10, 0x8b, 0xfa, 0xd7, 0xd4, 0x9f, 0x91, 0xae,
	0xc1, 0x06, 0xf7, 0xdd, 0x09, 0xf1, 0x6f, 0xe2, 0x35, 0xa1, 0x44, 0xa4, 0xc3, 0x96, 0x47, 0xdf,
	0xd8, 0x13, 0x1a, 0x10, 0x7b, 0xec, 0x8a, 0xb0, 0x5d, 0xb2, 0x07, 0x05, 0x5c, 0xf4, 0xe8, 0x9b,
	0xd0, 0xd1, 0x99, 0x2b, 0x02, 0xfd, 0x0f, 0xa8, 0x2e, 0x3a, 0x15, 0x7c, 0x11, 0xab, 0x2d, 0x60,
	0x1f, 0x4c, 0xbb, 0x84, 0xe9, 0x80, 0x79, 0x03, 0x77, 0x4c, 0x3f, 0x5b, 0x6f, 0x1d, 0xc1, 0x56,
	0xca, 0xe9, 0x43, 0x53, 0xf8, 0x5d, 0x30, 0x97, 0xfb, 0xb0, 0x2c, 0x68, 0x1b, 0x8a, 0xc7, 0xbf,
	0xb6, 0xce, 0xdb, 0xa6, 0x7d, 0xde, 0x3d, 0x31, 0x2b, 0x6b, 0xa8, 0x02, 0xa5, 0x63, 0x6c, 0xb6,
	0x2e, 0x4c, 0xbb, 0x8d, 0xbb, 0xbf, 0xf5, 0x2a, 0x5a, 0xa8, 0x69, 0x9d, 0x9c, 0xd8, 0x17, 0x5d,
	0xa5, 0xc9, 0xa0, 0x3d, 0xd8, 0xc1, 0x66, 0xa7, 0xfb, 0xca, 0xb4, 0x7f, 0xc1, 0xdd, 0x8e, 0x52,
	0x67, 0x43, 0xb5, 0xf2, 0x75, 0xd1, 0xb5, 0x7b, 0xf8, 0xb4, 0xd3, 0xc2, 0xbf, 0x57, 0x72, 0x87,
	0xef, 0xb3, 0x50, 0x3c, 0x21, 0x51, 0x92, 0xdd, 0x01, 0x45, 0xdf, 0x42, 0xb6, 0x4d, 0x03, 0x54,
	0x4e, 0x3a, 0x45, 0x2e, 0xfc, 0xfa, 0xf6, 0x9c, 0x2c, 0x78, 0x68, 0x67, 0xa5, 0xed, 0xac, 0x3b,
	0x76, 0xf1, 0x5a, 0xff, 0x11, 0x0a, 0xc9, 0xd2, 0x43, 0xd5, 0xf8, 0x36, 0xbd, 0x98, 0xeb, 0x7b,
	0x4b, 0xb4, 0x82, 0xa3, 0x1e, 0xec, 0x2c, 0x6c, 0x26, 0xf4, 0x24, 0xc5, 0x63, 0x61, 0x05, 0xd6,
	0xf7, 0x57, 0xdc, 0x0a, 0x1e, 0x8e, 0x43, 0x34, 0xf3, 0x68, 0x27, 0x6d, 0x18, 0xb1, 0x40, 0x77,
	0x55, 0x82, 0xa3, 0x9f, 0xa1, 0x98, 0x2a, 0x09, 0xfa, 0x62, 0xc9, 0xf8, 0x84, 0xd0, 0x47, 0x4b,
	0xf5, 0x82, 0xa3, 0x0e, 0x54, 0xee, 0x36, 0x30, 0x7a, 0x1c, 0x1b, 0x2f, 0x99, 0x97, 0xfa, 0x93,
	0x8f, 0x5f, 0x46, 0xb9, 0x4c, 0x1a, 0x6b, 0x96, 0xcb, 0x74, 0x03, 0xcf, 0x72, 0x39, 0xd7, 0x81,
	0x2f, 0xaa, 0xef, 0xfe, 0x6f, 0xac, 0xbd, 0xbd, 0x6d, 0x68, 0xef, 0x6e, 0x1b, 0xda, 0x7f, 0xb7,
	0x0d, 0xed, 0xaf, 0xf7, 0x8d, 0xb5, 0x7e, 0x5e, 0xfe, 0x54, 0x3c, 0xfb, 0x10, 0x00, 0x00, 0xff,
	0xff, 0xc2, 0x11, 0xaa, 0x8e, 0x4d, 0x09, 0x00, 0x00,
}
